/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'N1405571' at '09.05.17 15:51' with Gradle 2.3
 *
 * @author N1405571, @date 09.05.17 15:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
